---
x-app: &app
  image: sombriks/worhou:${VERSION:-latest}
  restart: unless-stopped
  environment:
    VERSION: ${VERSION:-latest}
    DB_PASSWORD: ${DB_PASSWORD:-worhou}
    DB_USER: ${DB_USER:-worhou}
    DB_HOST: ${DB_HOST:-db}
    NODE_ENV: ${NODE_ENV:-production}
    HOST: ${HOST:-0.0.0.0}
    PORT: ${PORT:-3000}
    AUTH_KEY: ${AUTH_KEY}
    AUTH_EXPIRES_IN: ${AUTH_EXPIRES_IN:-1d}
    EMAIL_API_URL: ${EMAIL_API_URL}
    EMAIL_API_USERNAME: ${EMAIL_API_USERNAME}
    EMAIL_API_PASSWORD: ${EMAIL_API_PASSWORD}
  healthcheck:
    test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:$PORT/ || exit 1" ]
    start_period: 5s
    interval: 30s
    timeout: 5s
  depends_on:
    db:
      condition: service_healthy
name: worhou
services:
  app1:
    <<: *app
    ports:
      - "3010:${PORT:-3000}"
  app2:
    <<: *app
    ports:
      - "3011:${PORT:-3000}"
  app3:
    <<: *app
    ports:
      - "3012:${PORT:-3000}"
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-worhou}
      POSTGRES_USER: ${DB_USER:-worhou}
      POSTGRES_DB: ${DB_USER:-worhou}
    volumes:
      - type: bind
        source: ${PG_DATA:-../../pg-data}
        target: /var/lib/postgresql
        bind:
          selinux: Z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
